### ISSUE TITLE
Definir a Arquitetura do Software

### ISSUE THREAD

**Issue by victorsdantas** [victorsdantas/projeto-pereira-aguas#11]
Definir a arquitetura a usar no projeto

**Comment by victorsdantas** [comment]
Para o projeto, na camada de dados teremos o MySQL e o será desenvolvido a principio em PHP.

**Comment by tacianosilva** [comment]
@victorsdantas se uma atividade for finalizada ela deve ser fechada! O resultado das tarefas (issue) do tipo documentação deve ter seus resultados colocados na página wiki do github.
