### ISSUE TITLE
Criar Diagrama de Entidade Relacionamento

### ISSUE THREAD

**Issue by tacianosilva** [victorsdantas/projeto-pereira-aguas#2]
O gerente @victorsdantas deve definir quem vai trabalhar nesta tarefa, pode ser um ou mais membros. A equipe deve informar quanto tempo levou para terminar a tarefa.

**Comment by victorsdantas** [comment]
Atividade Concluida. A equipe começou a fazer na noite do dia 03/10/2017 e terminou em mais ou menos 24 horas.
Abaixo está o link da tarefa que contém o diretório para a imagem do diagrama.
[Tarefa DER](https://github.com/victorsdantas/projeto-pereira-aguas/issues/9)
