### ISSUE TITLE
Criar página Wiki com os papéis da equipe e a matriz de competência

### ISSUE THREAD

**Issue by tacianosilva** [victorsdantas/projeto-pereira-aguas#7]
Criar página Wiki com tabelas com os papéis da equipe e a matriz de competência. Criei um milestone de definição apenas para colocar o resumo da equipe.

**Comment by victorsdantas** [comment]
Atividade concluída. Nos links abaixo estão as páginas pedidas.
[Equipe e Definição de Papéis ](https://github.com/victorsdantas/projeto-pereira-aguas/wiki/Equipe-e-Defini%C3%A7%C3%A3o-dos-Pap%C3%A9is) 
[Matriz de Competências ](https://github.com/victorsdantas/projeto-pereira-aguas/wiki/Matriz-de-Compet%C3%AAncias)
