### ISSUE TITLE
Criar página Wiki com o resumo do documento de visão

### ISSUE THREAD

**Issue by tacianosilva** [victorsdantas/projeto-pereira-aguas#8]
Criar página wiki com o resumo do documento de visão. Ou seja, deve conter um pequena descrição e a lista de requisitos do sistema.

**Comment by victorsdantas** [comment]
Atividade Concluida.
[Resumo do Documento de Visão](https://github.com/victorsdantas/projeto-pereira-aguas/wiki/Resumo-Documento-de-Vis%C3%A3o)
